package com.novelot.greendao.dao;

import android.database.sqlite.SQLiteDatabase;

import java.util.Map;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.AbstractDaoSession;
import de.greenrobot.dao.identityscope.IdentityScopeType;
import de.greenrobot.dao.internal.DaoConfig;

import com.novelot.greendao.dao.DownloadTask;

import com.novelot.greendao.dao.DownloadTaskDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig downloadTaskDaoConfig;

    private final DownloadTaskDao downloadTaskDao;

    public DaoSession(SQLiteDatabase db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        downloadTaskDaoConfig = daoConfigMap.get(DownloadTaskDao.class).clone();
        downloadTaskDaoConfig.initIdentityScope(type);

        downloadTaskDao = new DownloadTaskDao(downloadTaskDaoConfig, this);

        registerDao(DownloadTask.class, downloadTaskDao);
    }
    
    public void clear() {
        downloadTaskDaoConfig.getIdentityScope().clear();
    }

    public DownloadTaskDao getDownloadTaskDao() {
        return downloadTaskDao;
    }

}
